
name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Downloading & Installing Essentials
        run: |
          $attempts = 0
          $maxAttempts = 5
          while ($attempts -lt $maxAttempts) {
            try {
              Write-Host "Downloading essentials (Attempt $($attempts + 1))..."
              Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
              cmd /c Downloads.bat
              break
            } catch {
              Write-Host "Download failed. Retrying..."
              Start-Sleep -Seconds 10
              $attempts++
              if ($attempts -eq $maxAttempts) {
                throw "Failed to download essentials after $maxAttempts attempts."
              }
            }
          }

      - name: Log In To AnyDesk
        run: |
          Write-Host "Starting AnyDesk login..."
          try {
            cmd /c show.bat
          } catch {
            Write-Host "Failed to log in to AnyDesk. Ensure network connectivity."
            throw $_
          }

      - name: Time Counter
        run: python time.py

      - name: Monitoring and Reconnection (Optional)
        run: |
          Write-Host "Monitoring connection status..."
          while ($true) {
            Start-Sleep -Seconds 60
            if (!(Test-Connection -ComputerName 8.8.8.8 -Count 1 -Quiet)) {
              Write-Host "Connection lost. Attempting reconnection..."
              Restart-Computer
            } else {
              Write-Host "Connection stable."
            }
          }
